[database]
name = "todo_app_test"
max_connections = 10
connection_timeout = 10

[logging]
level = "debug"

[rate_limiting]
requests = 1000
duration = 60

[feature_flags]
enable_registration = true
enable_social_login = true
